name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Spring Boot
        run: mvn -B package --file springboot/app/pom.xml

      - name: Build Backend Image
        run: docker build -t spring-app ./springboot/app

      - name: Tag Backend Image
        run: docker tag spring-app ${{ secrets.DOCKERHUB_USERNAME }}/spring-app

      - name: Build Frontend Image
        run: docker build -t angular-app ./angular-app

      - name: Tag Frontend Image
        run: docker tag angular-app ${{ secrets.DOCKERHUB_USERNAME }}/angular-app

      - name: Push Backend Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-app

      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/angular-app

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Application
        run: docker-compose up -d
      - name: Show project structure
        run: ls -R



